# Generated by Django 6.0.2 on 2026-03-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Link for the client to pay (Optional)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_qr',
            field=models.ImageField(blank=True, help_text='QR Code for the client to scan and pay', null=True, upload_to='qrcodes/'),
        ),
    ]
