# Generated by Django 6.0.2 on 2026-03-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_payment_link_invoice_payment_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the client confirmed payment', null=True),
        ),
    ]
