# Generated by Django 6.0.2 on 2026-03-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_paid_at_to_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='milestone',
        ),
    ]
