# Generated by Django 6.0.2 on 2026-03-01 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deliverable',
            field=models.FileField(blank=True, null=True, upload_to='deliverables/'),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverable_note',
            field=models.TextField(blank=True, help_text='Notes from the freelancer about the deliverable'),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverable_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='freelancer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Whether the assigned freelancer has accepted or rejected this project', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='freelancer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'freelancer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
