# Generated by Django 6.0.2 on 2026-03-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_deliverable_project_deliverable_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='A visual preview of the project', null=True, upload_to='previews/'),
        ),
        migrations.AddField(
            model_name='project',
            name='preview_link',
            field=models.URLField(blank=True, help_text='A live link to preview the product', max_length=500, null=True),
        ),
    ]
