# Generated by Django 6.0.2 on 2026-03-11 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_preview_image_project_preview_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected budget for this project', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount the freelancer requires for payment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Payment link for the client', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_qr',
            field=models.ImageField(blank=True, help_text='QR code for payment', null=True, upload_to='payment_qr/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='A brief message about why you want this project')),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Your proposed rate for this project', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(limit_choices_to={'role': 'freelancer'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'freelancer')},
            },
        ),
    ]
