# Generated by Django 6.0.2 on 2026-03-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_budget_project_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='portfolio_file',
            field=models.FileField(blank=True, help_text='Attach a portfolio, resume, or work sample (PDF, DOC, image, ZIP, etc.)', null=True, upload_to='portfolios/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='previews/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_images', to='projects.project')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
