# Generated by Django 6.0.2 on 2026-03-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectapplication_portfolio_file_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='amount',
        ),
    ]
